from PyQt6 import QtCore, QtGui, QtWidgets
import ui_files.resourcesFile


class UI_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 550)
        MainWindow.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 550))
        MainWindow.setMaximumSize(QtCore.QSize(1300, 660))
        MainWindow.setStyleSheet("*{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    background: transparent;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"    color: #fff;\n"
"}\n"
"\n"
"#centralwidget{\n"
"    background-color: #1f232a;\n"
"}\n"
"\n"
"#leftMenuSubContainer{\n"
"    background-color: #16191d;\n"
"}\n"
"\n"
"#leftMenuSubContainer QPushButton{\n"
"    text-align: left;\n"
"    padding: 5px 10px;\n"
"    border-top-ledt-radius: 10px;\n"
"    border-bottom-left-raidus: 10px;\n"
"}\n"
"\n"
"#frame_4, #frame_8, #popupNotificationSubContainer{\n"
"    background-color:#16191d;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#centerMenuSubContainer, #rightMenuSubContainer {\n"
"    background-color: #2c313c;\n"
"}\n"
"\n"
"#headerContainer, #footerContainer{\n"
"    background-color: #2c313c;\n"
"}\n"
"\n"
"#closeBtn {\n"
"    color: #fff;\n"
"}\n"
"\n"
"#closeBtn:hover {\n"
"    color: #fff;\n"
"    background-color: #500000;\n"
"}\n"
"\n"
"#minimizeBtn, #restoreBtn {\n"
"    color: #fff;\n"
"}\n"
"\n"
"#minimizeBtn:hover, #restoreBtn:hover {\n"
"    color: #fff;\n"
"    background-color: gray;\n"
"}\n"
"\n"
"#btnProfile, #btnNotification, #btnProfile,  #btnNotification, #btnShowMoreMenu {\n"
"    border-radius: 10px; \n"
"}\n"
"\n"
"#btnProfile:hover, #btnNotification:hover, #btnProfile:hover,  #btnNotification:hover, #btnShowMoreMenu:hover {\n"
"    background-color: gray;\n"
"    border-radius: 10px; \n"
"}\n"
"\n"
"#pushButtonInicio, #pushButtonAsistencia, #pushButtonReporte {\n"
"    border-radius: 10px; \n"
"}\n"
"\n"
"#pushButtonInicio:hover, #pushButtonAsistencia:hover,  #pushButtonReporte:hover {\n"
"    background-color: gray;\n"
"    border-radius: 10px; \n"
"}\n"
"\n"
"#pushButtonConfiguracion, #pushButtonAcercaDe, #pushButtonAyuda {\n"
"    border-radius: 10px; \n"
"}\n"
"\n"
"#pushButtonConfiguracion:hover, #pushButtonAcercaDe:hover,  #pushButtonAyuda:hover {\n"
"    background-color: gray;\n"
"    border-radius: 10px; \n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftMenuContainer = QtWidgets.QWidget(parent=self.centralwidget)
        self.leftMenuContainer.setObjectName("leftMenuContainer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.leftMenuContainer)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.leftMenuSubContainer = QtWidgets.QWidget(parent=self.leftMenuContainer)
        self.leftMenuSubContainer.setObjectName("leftMenuSubContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.leftMenuSubContainer)
        self.verticalLayout_2.setContentsMargins(5, 5, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=self.leftMenuSubContainer)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2.addWidget(self.frame, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.frame_2 = QtWidgets.QFrame(parent=self.leftMenuSubContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.pushButtonInicio = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButtonInicio.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButtonInicio.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/home.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonInicio.setIcon(icon)
        self.pushButtonInicio.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonInicio.setObjectName("pushButtonInicio")
        self.verticalLayout_4.addWidget(self.pushButtonInicio)
        self.pushButtonAsistencia = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButtonAsistencia.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/user-check.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonAsistencia.setIcon(icon1)
        self.pushButtonAsistencia.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonAsistencia.setObjectName("pushButtonAsistencia")
        self.verticalLayout_4.addWidget(self.pushButtonAsistencia)
        self.pushButtonReporte = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButtonReporte.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/printer.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonReporte.setIcon(icon2)
        self.pushButtonReporte.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonReporte.setObjectName("pushButtonReporte")
        self.verticalLayout_4.addWidget(self.pushButtonReporte)
        self.verticalLayout_2.addWidget(self.frame_2, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.frame_3 = QtWidgets.QFrame(parent=self.leftMenuSubContainer)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButtonConfiguracion = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButtonConfiguracion.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/settings.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonConfiguracion.setIcon(icon3)
        self.pushButtonConfiguracion.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonConfiguracion.setObjectName("pushButtonConfiguracion")
        self.verticalLayout_5.addWidget(self.pushButtonConfiguracion)
        self.pushButtonAcercaDe = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButtonAcercaDe.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/info.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonAcercaDe.setIcon(icon4)
        self.pushButtonAcercaDe.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonAcercaDe.setObjectName("pushButtonAcercaDe")
        self.verticalLayout_5.addWidget(self.pushButtonAcercaDe)
        self.pushButtonAyuda = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButtonAyuda.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/help-circle.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonAyuda.setIcon(icon5)
        self.pushButtonAyuda.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonAyuda.setObjectName("pushButtonAyuda")
        self.verticalLayout_5.addWidget(self.pushButtonAyuda)
        self.verticalLayout_2.addWidget(self.frame_3, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.verticalLayout.addWidget(self.leftMenuSubContainer)
        self.horizontalLayout.addWidget(self.leftMenuContainer)
        self.centerMenuContainer = QtWidgets.QWidget(parent=self.centralwidget)
        self.centerMenuContainer.setObjectName("centerMenuContainer")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centerMenuContainer)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.centerMenuSubContainer = QtWidgets.QWidget(parent=self.centerMenuContainer)
        self.centerMenuSubContainer.setMinimumSize(QtCore.QSize(200, 0))
        self.centerMenuSubContainer.setObjectName("centerMenuSubContainer")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centerMenuSubContainer)
        self.verticalLayout_6.setContentsMargins(5, 8, 5, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_4 = QtWidgets.QFrame(parent=self.centerMenuSubContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.frame_4)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.btnCloseMoreMenu = QtWidgets.QPushButton(parent=self.frame_4)
        self.btnCloseMoreMenu.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCloseMoreMenu.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/x-circle.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnCloseMoreMenu.setIcon(icon6)
        self.btnCloseMoreMenu.setIconSize(QtCore.QSize(24, 24))
        self.btnCloseMoreMenu.setObjectName("btnCloseMoreMenu")
        self.horizontalLayout_3.addWidget(self.btnCloseMoreMenu, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout_6.addWidget(self.frame_4, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centerMenuSubContainer)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.stackedWidget.setMaximumSize(QtCore.QSize(1900, 1820))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_2 = QtWidgets.QLabel(parent=self.page)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_3 = QtWidgets.QLabel(parent=self.page_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_9.addWidget(self.label_3)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_4 = QtWidgets.QLabel(parent=self.page_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.stackedWidget.addWidget(self.page_3)
        self.verticalLayout_6.addWidget(self.stackedWidget)
        self.verticalLayout_3.addWidget(self.centerMenuSubContainer, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.horizontalLayout.addWidget(self.centerMenuContainer)
        self.mainBodyContainer = QtWidgets.QWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainBodyContainer.sizePolicy().hasHeightForWidth())
        self.mainBodyContainer.setSizePolicy(sizePolicy)
        self.mainBodyContainer.setStyleSheet("")
        self.mainBodyContainer.setObjectName("mainBodyContainer")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.mainBodyContainer)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.headerContainer = QtWidgets.QWidget(parent=self.mainBodyContainer)
        self.headerContainer.setMinimumSize(QtCore.QSize(0, 30))
        self.headerContainer.setMaximumSize(QtCore.QSize(16777215, 40))
        self.headerContainer.setObjectName("headerContainer")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.headerContainer)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_5 = QtWidgets.QFrame(parent=self.headerContainer)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_6.setContentsMargins(0, 5, 0, -1)
        self.horizontalLayout_6.setSpacing(8)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_11 = QtWidgets.QFrame(parent=self.frame_5)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 35))
        self.frame_11.setMaximumSize(QtCore.QSize(40, 50))
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 4)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.btnShowMoreMenu = QtWidgets.QPushButton(parent=self.frame_11)
        self.btnShowMoreMenu.setMinimumSize(QtCore.QSize(30, 35))
        self.btnShowMoreMenu.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnShowMoreMenu.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/arrow-right.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnShowMoreMenu.setIcon(icon7)
        self.btnShowMoreMenu.setIconSize(QtCore.QSize(24, 24))
        self.btnShowMoreMenu.setObjectName("btnShowMoreMenu")
        self.verticalLayout_14.addWidget(self.btnShowMoreMenu)
        self.horizontalLayout_6.addWidget(self.frame_11, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tricappIcon = QtWidgets.QLabel(parent=self.frame_5)
        self.tricappIcon.setMinimumSize(QtCore.QSize(40, 35))
        self.tricappIcon.setMaximumSize(QtCore.QSize(40, 35))
        self.tricappIcon.setText("")
        self.tricappIcon.setPixmap(QtGui.QPixmap(":/icons/icons/AppIcon.ico"))
        self.tricappIcon.setScaledContents(True)
        self.tricappIcon.setIndent(0)
        self.tricappIcon.setOpenExternalLinks(False)
        self.tricappIcon.setObjectName("tricappIcon")
        self.horizontalLayout_6.addWidget(self.tricappIcon)
        self.label_6 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_6.setMinimumSize(QtCore.QSize(0, 35))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.horizontalLayout_5.addWidget(self.frame_5, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.frame_6 = QtWidgets.QFrame(parent=self.headerContainer)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_7.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btnNotification = QtWidgets.QPushButton(parent=self.frame_6)
        self.btnNotification.setMinimumSize(QtCore.QSize(30, 35))
        self.btnNotification.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnNotification.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/bell.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnNotification.setIcon(icon8)
        self.btnNotification.setIconSize(QtCore.QSize(18, 18))
        self.btnNotification.setObjectName("btnNotification")
        self.horizontalLayout_7.addWidget(self.btnNotification)
        self.btnProfile = QtWidgets.QPushButton(parent=self.frame_6)
        self.btnProfile.setMinimumSize(QtCore.QSize(30, 35))
        self.btnProfile.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnProfile.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/user.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnProfile.setIcon(icon9)
        self.btnProfile.setIconSize(QtCore.QSize(20, 20))
        self.btnProfile.setObjectName("btnProfile")
        self.horizontalLayout_7.addWidget(self.btnProfile)
        self.horizontalLayout_5.addWidget(self.frame_6, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.frame_7 = QtWidgets.QFrame(parent=self.headerContainer)
        self.frame_7.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_7.setStyleSheet("")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.minimizeBtn = QtWidgets.QPushButton(parent=self.frame_7)
        self.minimizeBtn.setMinimumSize(QtCore.QSize(40, 30))
        self.minimizeBtn.setMaximumSize(QtCore.QSize(100, 100))
        self.minimizeBtn.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/minus.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.minimizeBtn.setIcon(icon10)
        self.minimizeBtn.setIconSize(QtCore.QSize(17, 17))
        self.minimizeBtn.setObjectName("minimizeBtn")
        self.horizontalLayout_4.addWidget(self.minimizeBtn)
        self.restoreBtn = QtWidgets.QPushButton(parent=self.frame_7)
        self.restoreBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.restoreBtn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.restoreBtn.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/icons/square.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.restoreBtn.setIcon(icon11)
        self.restoreBtn.setIconSize(QtCore.QSize(13, 13))
        self.restoreBtn.setObjectName("restoreBtn")
        self.horizontalLayout_4.addWidget(self.restoreBtn)
        self.closeBtn = QtWidgets.QPushButton(parent=self.frame_7)
        self.closeBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.closeBtn.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/icons/x.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.closeBtn.setIcon(icon12)
        self.closeBtn.setIconSize(QtCore.QSize(17, 17))
        self.closeBtn.setObjectName("closeBtn")
        self.horizontalLayout_4.addWidget(self.closeBtn)
        self.horizontalLayout_5.addWidget(self.frame_7, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout_10.addWidget(self.headerContainer, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.mainBodyContent = QtWidgets.QWidget(parent=self.mainBodyContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainBodyContent.sizePolicy().hasHeightForWidth())
        self.mainBodyContent.setSizePolicy(sizePolicy)
        self.mainBodyContent.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.mainBodyContent.setObjectName("mainBodyContent")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.mainBodyContent)
        self.horizontalLayout_8.setContentsMargins(0, -1, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.mainContentsContainer = QtWidgets.QWidget(parent=self.mainBodyContent)
        self.mainContentsContainer.setObjectName("mainContentsContainer")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.mainContentsContainer)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.mainStackedWidget = QtWidgets.QStackedWidget(parent=self.mainContentsContainer)
        self.mainStackedWidget.setObjectName("mainStackedWidget")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.imgWolf = QtWidgets.QLabel(parent=self.page_6)
        self.imgWolf.setGeometry(QtCore.QRect(9, 9, 1200, 650))
        self.imgWolf.setMinimumSize(QtCore.QSize(1150, 650))
        self.imgWolf.setMaximumSize(QtCore.QSize(1150, 650))
        self.imgWolf.setText("")
        self.imgWolf.setPixmap(QtGui.QPixmap(":/images/darkWolf.png"))
        self.imgWolf.setScaledContents(True)
        self.imgWolf.setWordWrap(False)
        self.imgWolf.setObjectName("imgWolf")
        self.labelaaa = QtWidgets.QLabel(parent=self.page_6)
        self.labelaaa.setGeometry(QtCore.QRect(30, 120, 331, 131))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.labelaaa.setFont(font)
        self.labelaaa.setObjectName("labelaaa")
        self.mainStackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.page_7)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_11 = QtWidgets.QLabel(parent=self.page_7)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_16.addWidget(self.label_11)
        self.mainStackedWidget.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.page_8)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_12 = QtWidgets.QLabel(parent=self.page_8)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_19.addWidget(self.label_12)
        self.mainStackedWidget.addWidget(self.page_8)
        self.horizontalLayout_14.addWidget(self.mainStackedWidget)
        self.horizontalLayout_8.addWidget(self.mainContentsContainer)
        self.rightMenuContainer = QtWidgets.QWidget(parent=self.mainBodyContent)
        self.rightMenuContainer.setMinimumSize(QtCore.QSize(200, 0))
        self.rightMenuContainer.setObjectName("rightMenuContainer")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.rightMenuContainer)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.rightMenuSubContainer = QtWidgets.QWidget(parent=self.rightMenuContainer)
        self.rightMenuSubContainer.setObjectName("rightMenuSubContainer")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.rightMenuSubContainer)
        self.verticalLayout_12.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_12.setSpacing(5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_8 = QtWidgets.QFrame(parent=self.rightMenuSubContainer)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.btnCloseProfile = QtWidgets.QPushButton(parent=self.frame_8)
        self.btnCloseProfile.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCloseProfile.setText("")
        self.btnCloseProfile.setIcon(icon6)
        self.btnCloseProfile.setIconSize(QtCore.QSize(24, 24))
        self.btnCloseProfile.setObjectName("btnCloseProfile")
        self.horizontalLayout_9.addWidget(self.btnCloseProfile, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout_12.addWidget(self.frame_8)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(parent=self.rightMenuSubContainer)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.page_4)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(parent=self.page_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.stackedWidget_2.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_9 = QtWidgets.QLabel(parent=self.page_5)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_13.addWidget(self.label_9)
        self.stackedWidget_2.addWidget(self.page_5)
        self.verticalLayout_12.addWidget(self.stackedWidget_2)
        self.verticalLayout_11.addWidget(self.rightMenuSubContainer)
        self.horizontalLayout_8.addWidget(self.rightMenuContainer, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout_10.addWidget(self.mainBodyContent)
        self.popupNotificationContainer = QtWidgets.QWidget(parent=self.mainBodyContainer)
        self.popupNotificationContainer.setObjectName("popupNotificationContainer")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.popupNotificationContainer)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.popupNotificationSubContainer = QtWidgets.QWidget(parent=self.popupNotificationContainer)
        self.popupNotificationSubContainer.setObjectName("popupNotificationSubContainer")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.popupNotificationSubContainer)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_14 = QtWidgets.QLabel(parent=self.popupNotificationSubContainer)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_18.addWidget(self.label_14)
        self.frame_9 = QtWidgets.QFrame(parent=self.popupNotificationSubContainer)
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_13 = QtWidgets.QLabel(parent=self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_11.addWidget(self.label_13)
        self.btnCloseNotification = QtWidgets.QPushButton(parent=self.frame_9)
        self.btnCloseNotification.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCloseNotification.setText("")
        self.btnCloseNotification.setIcon(icon6)
        self.btnCloseNotification.setIconSize(QtCore.QSize(24, 24))
        self.btnCloseNotification.setObjectName("btnCloseNotification")
        self.horizontalLayout_11.addWidget(self.btnCloseNotification, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout_18.addWidget(self.frame_9)
        self.verticalLayout_17.addWidget(self.popupNotificationSubContainer)
        self.verticalLayout_10.addWidget(self.popupNotificationContainer)
        self.footerContainer = QtWidgets.QWidget(parent=self.mainBodyContainer)
        self.footerContainer.setObjectName("footerContainer")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.footerContainer)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_10 = QtWidgets.QFrame(parent=self.footerContainer)
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_15 = QtWidgets.QLabel(parent=self.frame_10)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_13.addWidget(self.label_15)
        self.horizontalLayout_12.addWidget(self.frame_10)
        self.sizeGrip = QtWidgets.QFrame(parent=self.footerContainer)
        self.sizeGrip.setMinimumSize(QtCore.QSize(30, 30))
        self.sizeGrip.setMaximumSize(QtCore.QSize(30, 30))
        self.sizeGrip.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.sizeGrip.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.sizeGrip.setObjectName("sizeGrip")
        self.horizontalLayout_12.addWidget(self.sizeGrip)
        self.verticalLayout_10.addWidget(self.footerContainer)
        self.horizontalLayout.addWidget(self.mainBodyContainer)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionSalir = QtGui.QAction(parent=MainWindow)
        self.actionSalir.setObjectName("actionSalir")

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.mainStackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gestión de Asistencia en Aula"))
        self.pushButtonInicio.setToolTip(_translate("MainWindow", "Inicio"))
        self.pushButtonInicio.setText(_translate("MainWindow", "Inicio"))
        self.pushButtonAsistencia.setToolTip(_translate("MainWindow", "Tomar la asistencia"))
        self.pushButtonAsistencia.setText(_translate("MainWindow", "Asistencia"))
        self.pushButtonReporte.setToolTip(_translate("MainWindow", "Ver reporte de asistencia"))
        self.pushButtonReporte.setText(_translate("MainWindow", "Reporte"))
        self.pushButtonConfiguracion.setToolTip(_translate("MainWindow", "Ir a configuración"))
        self.pushButtonConfiguracion.setText(_translate("MainWindow", "Configuración"))
        self.pushButtonAcercaDe.setToolTip(_translate("MainWindow", "Ver información"))
        self.pushButtonAcercaDe.setText(_translate("MainWindow", "Acerca de"))
        self.pushButtonAyuda.setToolTip(_translate("MainWindow", "Ver la ayuda"))
        self.pushButtonAyuda.setText(_translate("MainWindow", "Ayuda"))
        self.label.setText(_translate("MainWindow", "Información"))
        self.btnCloseMoreMenu.setToolTip(_translate("MainWindow", "Cerrar Menú"))
        self.label_2.setText(_translate("MainWindow", "Settings"))
        self.label_3.setText(_translate("MainWindow", "Help"))
        self.label_4.setText(_translate("MainWindow", "Information"))
        self.label_6.setText(_translate("MainWindow", "TRICAPP"))
        self.btnNotification.setToolTip(_translate("MainWindow", "Más"))
        self.btnProfile.setToolTip(_translate("MainWindow", "Perfil"))
        self.minimizeBtn.setToolTip(_translate("MainWindow", "Minimizar"))
        self.restoreBtn.setToolTip(_translate("MainWindow", "Restaurar"))
        self.closeBtn.setToolTip(_translate("MainWindow", "Cerrar"))
        self.labelaaa.setText(_translate("MainWindow", "El lobo y \n"
"la sociedad \n"
"¡PRIVADA! :V"))
        self.label_11.setText(_translate("MainWindow", "Asistencia"))
        self.label_12.setText(_translate("MainWindow", "Reporte"))
        self.label_7.setText(_translate("MainWindow", "Perfil"))
        self.btnCloseProfile.setToolTip(_translate("MainWindow", "Cerrar Menu"))
        self.label_8.setText(_translate("MainWindow", "Profile"))
        self.label_9.setText(_translate("MainWindow", "More..."))
        self.label_14.setText(_translate("MainWindow", "Notificación"))
        self.label_13.setText(_translate("MainWindow", "Mensaje"))
        self.btnCloseNotification.setToolTip(_translate("MainWindow", "Cerrar notificación"))
        self.label_15.setText(_translate("MainWindow", "Universidad Continental"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
