from PyQt6 import QtCore, QtGui, QtWidgets
import ui_files.resourcesFile


class UI_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 551)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 550))
        MainWindow.setMaximumSize(QtCore.QSize(1300, 551))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/AppIcon.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("*{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    background: transparent;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"    color: #fff;\n"
"}\n"
"\n"
"#centralwidget{\n"
"    background-color: #1f232a;\n"
"}\n"
"\n"
"#leftMenuSubContainer{\n"
"    background-color: #16191d;\n"
"}\n"
"\n"
"#leftMenuSubContainer QPushButton{\n"
"    text-align: left;\n"
"    padding: 5px 10px;\n"
"    border-top-ledt-radius: 10px;\n"
"    border-bottom-left-raidus: 10px;\n"
"}\n"
"\n"
"#frame_4, #frame_8, #popupNotificationSubContainer{\n"
"    background-color:#16191d;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#centerMenuSubContainer, #rightMenuSubContainer {\n"
"    background-color: #2c313c;\n"
"}\n"
"\n"
"#headerContainer, #footerContainer{\n"
"    background-color: #2c313c;\n"
"}\n"
"\n"
"#closeBtn {\n"
"    color: #fff;\n"
"}\n"
"\n"
"#closeBtn:hover {\n"
"    color: #fff;\n"
"    background-color: #500000;\n"
"}\n"
"\n"
"#minimizeBtn, #restoreBtn {\n"
"    color: #fff;\n"
"}\n"
"\n"
"#minimizeBtn:hover, #restoreBtn:hover {\n"
"    color: #fff;\n"
"    background-color: gray;\n"
"}\n"
"\n"
"#btnProfile, #btnNotification, #btnProfile,  #btnNotification, #btnShowMoreMenu {\n"
"    border-radius: 10px; \n"
"}\n"
"\n"
"#btnProfile:hover, #btnNotification:hover, #btnProfile:hover,  #btnNotification:hover, #btnShowMoreMenu:hover {\n"
"    background-color: gray;\n"
"    border-radius: 10px; \n"
"}\n"
"\n"
"#pushButtonInicio, #pushButtonAsistencia {\n"
"    border-radius: 10px; \n"
"}\n"
"\n"
"#pushButtonInicio:hover, #pushButtonAsistencia:hover {\n"
"    background-color: gray;\n"
"    border-radius: 10px; \n"
"}\n"
"\n"
"#pushButtonConfiguracion, #pushButtonAcercaDe, #btnCerrarSesion {\n"
"    border-radius: 10px; \n"
"}\n"
"\n"
"#pushButtonConfiguracion:hover, #pushButtonAcercaDe:hover,  #btnCerrarSesion:hover {\n"
"    background-color: gray;\n"
"    border-radius: 10px; \n"
"}\n"
"\n"
"#pushButtonInicio:pressed, #pushButtonAsistencia:pressed,\n"
"#pushButtonConfiguracion:pressed, #pushButtonAcercaDe:pressed, #btnCerrarSesion:pressed {\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"#btnCloseMoreMenu:hover {\n"
"   background-color: gray;\n"
"   border-radius: 12px;\n"
"}\n"
"\n"
"#btnCloseProfile:hover {\n"
"   background-color: gray;\n"
"   border-radius: 11px;\n"
"}\n"
"\n"
"#btnCloseNotification:hover {\n"
"   background-color: gray;\n"
"   border-radius: 12px;\n"
"}\n"
"\n"
"#btnTodo, #btnAsistio, #btnNoAsistio {\n"
"    background-color: rgb(170, 170, 127);\n"
"}\n"
"\n"
"#btnTodo:hover, #btnAsistio:hover, #btnNoAsistio:hover {\n"
"   background-color: rgb(200, 170, 127);\n"
"}\n"
"\n"
"#btnTodo:pressed, #btnAsistio:pressed, #btnNoAsistio:pressed {\n"
"   background-color: rgb(200, 180, 150);\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"#btnGeneraReporte {\n"
"    background-color: rgb(116, 10, 10);\n"
"}\n"
"\n"
"#btnGeneraReporte:hover {\n"
"   background-color: rgb(172, 88, 88);\n"
"}\n"
"\n"
"#btnGeneraReporte:pressed {\n"
"   background-color: rgb(230, 177, 177);\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftMenuContainer = QtWidgets.QWidget(parent=self.centralwidget)
        self.leftMenuContainer.setObjectName("leftMenuContainer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.leftMenuContainer)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.leftMenuSubContainer = QtWidgets.QWidget(parent=self.leftMenuContainer)
        self.leftMenuSubContainer.setObjectName("leftMenuSubContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.leftMenuSubContainer)
        self.verticalLayout_2.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(parent=self.leftMenuSubContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButtonInicio = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButtonInicio.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButtonInicio.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/home.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonInicio.setIcon(icon1)
        self.pushButtonInicio.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonInicio.setObjectName("pushButtonInicio")
        self.verticalLayout_4.addWidget(self.pushButtonInicio)
        self.pushButtonAsistencia = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButtonAsistencia.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/user-check.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonAsistencia.setIcon(icon2)
        self.pushButtonAsistencia.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonAsistencia.setObjectName("pushButtonAsistencia")
        self.verticalLayout_4.addWidget(self.pushButtonAsistencia)
        self.verticalLayout_2.addWidget(self.frame_2, 0, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.frame_3 = QtWidgets.QFrame(parent=self.leftMenuSubContainer)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 20)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButtonAcercaDe = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButtonAcercaDe.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/info.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonAcercaDe.setIcon(icon3)
        self.pushButtonAcercaDe.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonAcercaDe.setObjectName("pushButtonAcercaDe")
        self.verticalLayout_5.addWidget(self.pushButtonAcercaDe)
        self.verticalLayout_2.addWidget(self.frame_3, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.btnCerrarSesion = QtWidgets.QPushButton(parent=self.leftMenuSubContainer)
        self.btnCerrarSesion.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btnCerrarSesion.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/log-out.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnCerrarSesion.setIcon(icon4)
        self.btnCerrarSesion.setIconSize(QtCore.QSize(24, 24))
        self.btnCerrarSesion.setObjectName("btnCerrarSesion")
        self.verticalLayout_2.addWidget(self.btnCerrarSesion)
        self.verticalLayout.addWidget(self.leftMenuSubContainer)
        self.horizontalLayout.addWidget(self.leftMenuContainer)
        self.centerMenuContainer = QtWidgets.QWidget(parent=self.centralwidget)
        self.centerMenuContainer.setMaximumSize(QtCore.QSize(250, 16777215))
        self.centerMenuContainer.setObjectName("centerMenuContainer")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centerMenuContainer)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.centerMenuSubContainer = QtWidgets.QWidget(parent=self.centerMenuContainer)
        self.centerMenuSubContainer.setMinimumSize(QtCore.QSize(200, 0))
        self.centerMenuSubContainer.setObjectName("centerMenuSubContainer")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centerMenuSubContainer)
        self.verticalLayout_6.setContentsMargins(5, 8, 5, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_4 = QtWidgets.QFrame(parent=self.centerMenuSubContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.frame_4)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.btnCloseMoreMenu = QtWidgets.QPushButton(parent=self.frame_4)
        self.btnCloseMoreMenu.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCloseMoreMenu.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/x-circle.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnCloseMoreMenu.setIcon(icon5)
        self.btnCloseMoreMenu.setIconSize(QtCore.QSize(24, 24))
        self.btnCloseMoreMenu.setObjectName("btnCloseMoreMenu")
        self.horizontalLayout_3.addWidget(self.btnCloseMoreMenu, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout_6.addWidget(self.frame_4)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centerMenuSubContainer)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.stackedWidget.setMaximumSize(QtCore.QSize(1900, 1820))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_2 = QtWidgets.QLabel(parent=self.page)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_3 = QtWidgets.QLabel(parent=self.page_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_9.addWidget(self.label_3)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_4 = QtWidgets.QLabel(parent=self.page_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.stackedWidget.addWidget(self.page_3)
        self.verticalLayout_6.addWidget(self.stackedWidget)
        self.verticalLayout_3.addWidget(self.centerMenuSubContainer)
        self.horizontalLayout.addWidget(self.centerMenuContainer)
        self.mainBodyContainer = QtWidgets.QWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainBodyContainer.sizePolicy().hasHeightForWidth())
        self.mainBodyContainer.setSizePolicy(sizePolicy)
        self.mainBodyContainer.setStyleSheet("")
        self.mainBodyContainer.setObjectName("mainBodyContainer")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.mainBodyContainer)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.headerContainer = QtWidgets.QWidget(parent=self.mainBodyContainer)
        self.headerContainer.setMinimumSize(QtCore.QSize(0, 45))
        self.headerContainer.setMaximumSize(QtCore.QSize(16777215, 50))
        self.headerContainer.setObjectName("headerContainer")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.headerContainer)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_5 = QtWidgets.QFrame(parent=self.headerContainer)
        self.frame_5.setMaximumSize(QtCore.QSize(180, 16777215))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_6.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_11 = QtWidgets.QFrame(parent=self.frame_5)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 35))
        self.frame_11.setMaximumSize(QtCore.QSize(40, 50))
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 4)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.btnShowMoreMenu = QtWidgets.QPushButton(parent=self.frame_11)
        self.btnShowMoreMenu.setMinimumSize(QtCore.QSize(30, 35))
        self.btnShowMoreMenu.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnShowMoreMenu.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/arrow-right.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnShowMoreMenu.setIcon(icon6)
        self.btnShowMoreMenu.setIconSize(QtCore.QSize(24, 24))
        self.btnShowMoreMenu.setObjectName("btnShowMoreMenu")
        self.verticalLayout_14.addWidget(self.btnShowMoreMenu)
        self.horizontalLayout_6.addWidget(self.frame_11, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tricappIcon = QtWidgets.QLabel(parent=self.frame_5)
        self.tricappIcon.setMinimumSize(QtCore.QSize(40, 35))
        self.tricappIcon.setMaximumSize(QtCore.QSize(40, 35))
        self.tricappIcon.setText("")
        self.tricappIcon.setPixmap(QtGui.QPixmap(":/icons/icons/AppIcon.ico"))
        self.tricappIcon.setScaledContents(True)
        self.tricappIcon.setIndent(0)
        self.tricappIcon.setOpenExternalLinks(False)
        self.tricappIcon.setObjectName("tricappIcon")
        self.horizontalLayout_6.addWidget(self.tricappIcon)
        self.label_6 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_6.setMinimumSize(QtCore.QSize(0, 35))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.horizontalLayout_5.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(parent=self.headerContainer)
        self.frame_6.setMaximumSize(QtCore.QSize(80, 16777215))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btnNotification = QtWidgets.QPushButton(parent=self.frame_6)
        self.btnNotification.setMinimumSize(QtCore.QSize(30, 35))
        self.btnNotification.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btnNotification.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnNotification.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/bell.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnNotification.setIcon(icon7)
        self.btnNotification.setIconSize(QtCore.QSize(18, 18))
        self.btnNotification.setObjectName("btnNotification")
        self.horizontalLayout_7.addWidget(self.btnNotification)
        self.btnProfile = QtWidgets.QPushButton(parent=self.frame_6)
        self.btnProfile.setMinimumSize(QtCore.QSize(30, 35))
        self.btnProfile.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btnProfile.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnProfile.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/user.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnProfile.setIcon(icon8)
        self.btnProfile.setIconSize(QtCore.QSize(20, 20))
        self.btnProfile.setObjectName("btnProfile")
        self.horizontalLayout_7.addWidget(self.btnProfile)
        self.horizontalLayout_5.addWidget(self.frame_6, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.frame_7 = QtWidgets.QFrame(parent=self.headerContainer)
        self.frame_7.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_7.setMaximumSize(QtCore.QSize(100, 100))
        self.frame_7.setStyleSheet("")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_4.setContentsMargins(0, 0, 10, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.minimizeBtn = QtWidgets.QPushButton(parent=self.frame_7)
        self.minimizeBtn.setMinimumSize(QtCore.QSize(40, 30))
        self.minimizeBtn.setMaximumSize(QtCore.QSize(40, 30))
        self.minimizeBtn.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/minus.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.minimizeBtn.setIcon(icon9)
        self.minimizeBtn.setIconSize(QtCore.QSize(17, 17))
        self.minimizeBtn.setObjectName("minimizeBtn")
        self.horizontalLayout_4.addWidget(self.minimizeBtn)
        self.restoreBtn = QtWidgets.QPushButton(parent=self.frame_7)
        self.restoreBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.restoreBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.restoreBtn.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/square.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.restoreBtn.setIcon(icon10)
        self.restoreBtn.setIconSize(QtCore.QSize(13, 13))
        self.restoreBtn.setObjectName("restoreBtn")
        self.horizontalLayout_4.addWidget(self.restoreBtn)
        self.closeBtn = QtWidgets.QPushButton(parent=self.frame_7)
        self.closeBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.closeBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.closeBtn.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/icons/x.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.closeBtn.setIcon(icon11)
        self.closeBtn.setIconSize(QtCore.QSize(17, 17))
        self.closeBtn.setObjectName("closeBtn")
        self.horizontalLayout_4.addWidget(self.closeBtn)
        self.horizontalLayout_5.addWidget(self.frame_7, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout_10.addWidget(self.headerContainer)
        self.mainBodyContent = QtWidgets.QWidget(parent=self.mainBodyContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainBodyContent.sizePolicy().hasHeightForWidth())
        self.mainBodyContent.setSizePolicy(sizePolicy)
        self.mainBodyContent.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.mainBodyContent.setObjectName("mainBodyContent")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.mainBodyContent)
        self.horizontalLayout_8.setContentsMargins(0, -1, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.mainContentsContainer = QtWidgets.QWidget(parent=self.mainBodyContent)
        self.mainContentsContainer.setObjectName("mainContentsContainer")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.mainContentsContainer)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.mainStackedWidget = QtWidgets.QStackedWidget(parent=self.mainContentsContainer)
        self.mainStackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.mainStackedWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mainStackedWidget.setStyleSheet("")
        self.mainStackedWidget.setObjectName("mainStackedWidget")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.page_6)
        self.verticalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_30.setSpacing(0)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.widgetCursosWolf = QtWidgets.QWidget(parent=self.page_6)
        self.widgetCursosWolf.setMinimumSize(QtCore.QSize(0, 0))
        self.widgetCursosWolf.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widgetCursosWolf.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widgetCursosWolf.setObjectName("widgetCursosWolf")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widgetCursosWolf)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.widget = QtWidgets.QWidget(parent=self.widgetCursosWolf)
        self.widget.setMinimumSize(QtCore.QSize(200, 0))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget.setStyleSheet("background-color: black;")
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.lblSaludoInicio = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.lblSaludoInicio.setFont(font)
        self.lblSaludoInicio.setStyleSheet("")
        self.lblSaludoInicio.setObjectName("lblSaludoInicio")
        self.gridLayout.addWidget(self.lblSaludoInicio, 1, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.stackedWidgetCursos = QtWidgets.QStackedWidget(parent=self.widget)
        self.stackedWidgetCursos.setMinimumSize(QtCore.QSize(300, 0))
        self.stackedWidgetCursos.setMaximumSize(QtCore.QSize(400, 16777215))
        self.stackedWidgetCursos.setStyleSheet("")
        self.stackedWidgetCursos.setObjectName("stackedWidgetCursos")
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setMinimumSize(QtCore.QSize(300, 0))
        self.page_9.setMaximumSize(QtCore.QSize(400, 16777215))
        self.page_9.setObjectName("page_9")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.page_9)
        self.verticalLayout_22.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_22.setSpacing(6)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.btnCurso22888 = QtWidgets.QPushButton(parent=self.page_9)
        self.btnCurso22888.setMinimumSize(QtCore.QSize(0, 50))
        self.btnCurso22888.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCurso22888.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.btnCurso22888.setObjectName("btnCurso22888")
        self.verticalLayout_22.addWidget(self.btnCurso22888)
        self.btnCurso12341 = QtWidgets.QPushButton(parent=self.page_9)
        self.btnCurso12341.setMinimumSize(QtCore.QSize(0, 50))
        self.btnCurso12341.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCurso12341.setStyleSheet("background-color: rgb(170, 85, 0);")
        self.btnCurso12341.setObjectName("btnCurso12341")
        self.verticalLayout_22.addWidget(self.btnCurso12341)
        self.btnCurso12342 = QtWidgets.QPushButton(parent=self.page_9)
        self.btnCurso12342.setMinimumSize(QtCore.QSize(0, 50))
        self.btnCurso12342.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCurso12342.setStyleSheet("background-color: rgb(170, 170, 127);")
        self.btnCurso12342.setObjectName("btnCurso12342")
        self.verticalLayout_22.addWidget(self.btnCurso12342)
        self.btnCurso12343 = QtWidgets.QPushButton(parent=self.page_9)
        self.btnCurso12343.setMinimumSize(QtCore.QSize(0, 50))
        self.btnCurso12343.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCurso12343.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.btnCurso12343.setObjectName("btnCurso12343")
        self.verticalLayout_22.addWidget(self.btnCurso12343)
        self.stackedWidgetCursos.addWidget(self.page_9)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setMinimumSize(QtCore.QSize(300, 0))
        self.page_10.setMaximumSize(QtCore.QSize(400, 16777215))
        self.page_10.setObjectName("page_10")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.page_10)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.btnCurso30246 = QtWidgets.QPushButton(parent=self.page_10)
        self.btnCurso30246.setMinimumSize(QtCore.QSize(0, 50))
        self.btnCurso30246.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCurso30246.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.btnCurso30246.setObjectName("btnCurso30246")
        self.verticalLayout_23.addWidget(self.btnCurso30246)
        self.btnCurso12344 = QtWidgets.QPushButton(parent=self.page_10)
        self.btnCurso12344.setMinimumSize(QtCore.QSize(0, 50))
        self.btnCurso12344.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCurso12344.setStyleSheet("background-color: rgb(170, 85, 0);")
        self.btnCurso12344.setObjectName("btnCurso12344")
        self.verticalLayout_23.addWidget(self.btnCurso12344)
        self.btnCurso12345 = QtWidgets.QPushButton(parent=self.page_10)
        self.btnCurso12345.setMinimumSize(QtCore.QSize(0, 50))
        self.btnCurso12345.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCurso12345.setStyleSheet("background-color: rgb(170, 170, 127);")
        self.btnCurso12345.setObjectName("btnCurso12345")
        self.verticalLayout_23.addWidget(self.btnCurso12345)
        self.stackedWidgetCursos.addWidget(self.page_10)
        self.gridLayout.addWidget(self.stackedWidgetCursos, 2, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.horizontalLayout_11.addWidget(self.widget)
        self.imgWolf = QtWidgets.QLabel(parent=self.widgetCursosWolf)
        self.imgWolf.setMinimumSize(QtCore.QSize(200, 0))
        self.imgWolf.setMaximumSize(QtCore.QSize(300, 450))
        self.imgWolf.setText("")
        self.imgWolf.setPixmap(QtGui.QPixmap(":/images/darkWolfCutted.png"))
        self.imgWolf.setScaledContents(True)
        self.imgWolf.setWordWrap(False)
        self.imgWolf.setObjectName("imgWolf")
        self.horizontalLayout_11.addWidget(self.imgWolf, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignBottom)
        self.verticalLayout_30.addWidget(self.widgetCursosWolf)
        self.mainStackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.page_7)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.widget_5 = QtWidgets.QWidget(parent=self.page_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_12 = QtWidgets.QFrame(parent=self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setMaximumSize(QtCore.QSize(9999, 50))
        self.frame_12.setStyleSheet("")
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.frame_16 = QtWidgets.QFrame(parent=self.frame_12)
        self.frame_16.setMinimumSize(QtCore.QSize(70, 50))
        self.frame_16.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_11 = QtWidgets.QLabel(parent=self.frame_16)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(104, 199, 107)")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_18.addWidget(self.label_11)
        self.cmbBoxAsignatura = QtWidgets.QComboBox(parent=self.frame_16)
        self.cmbBoxAsignatura.setMaximumSize(QtCore.QSize(200, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.cmbBoxAsignatura.setFont(font)
        self.cmbBoxAsignatura.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.cmbBoxAsignatura.setStyleSheet("        QComboBox {\n"
"            border: 1px solid #444;\n"
"            border-radius: 5px;\n"
"            padding: 5px;\n"
"            background-color: #333;\n"
"            color: #FFF;\n"
"        }\n"
"\n"
"        QComboBox::drop-down {\n"
"            subcontrol-origin: padding;\n"
"            subcontrol-position: top right;\n"
"            width: 15px;\n"
"            border-left: 1px solid #444;\n"
"            background-color: #444;\n"
"        }\n"
"\n"
"        QComboBox::down-arrow {\n"
"            image: url(down_arrow.png); /* Coloca tu propia imagen de flecha aquí */\n"
"            width: 10px;\n"
"            height: 10px;\n"
"        }\n"
"\n"
"        QComboBox QAbstractItemView {\n"
"            border: 1px solid #444;\n"
"            border-radius: 5px;\n"
"            background-color: #333;\n"
"            selection-background-color: #555;\n"
"            selection-color: #FFF;\n"
"        }\n"
"\n"
"\n"
"#cmbBoxAsignatura:hover {\n"
"   background-color: rgb(118, 114, 114);\n"
"}\n"
"")
        self.cmbBoxAsignatura.setObjectName("cmbBoxAsignatura")
        self.cmbBoxAsignatura.addItem("")
        self.cmbBoxAsignatura.addItem("")
        self.cmbBoxAsignatura.addItem("")
        self.cmbBoxAsignatura.addItem("")
        self.cmbBoxAsignatura.addItem("")
        self.horizontalLayout_18.addWidget(self.cmbBoxAsignatura)
        self.horizontalLayout_15.addWidget(self.frame_16)
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.horizontalLayout_15.addItem(spacerItem)
        self.frame_14 = QtWidgets.QFrame(parent=self.frame_12)
        self.frame_14.setMinimumSize(QtCore.QSize(150, 50))
        self.frame_14.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_14.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelAsistioDNI = QtWidgets.QLabel(parent=self.frame_14)
        self.labelAsistioDNI.setMinimumSize(QtCore.QSize(130, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.labelAsistioDNI.setFont(font)
        self.labelAsistioDNI.setStyleSheet("color: rgb(104, 199, 107)")
        self.labelAsistioDNI.setObjectName("labelAsistioDNI")
        self.horizontalLayout_2.addWidget(self.labelAsistioDNI)
        self.lineEditDNI = QtWidgets.QLineEdit(parent=self.frame_14)
        self.lineEditDNI.setMinimumSize(QtCore.QSize(90, 0))
        self.lineEditDNI.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.lineEditDNI.setFont(font)
        self.lineEditDNI.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.lineEditDNI.setTabletTracking(False)
        self.lineEditDNI.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.lineEditDNI.setAutoFillBackground(False)
        self.lineEditDNI.setStyleSheet("color: black;\n"
"background-color: white;")
        self.lineEditDNI.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.lineEditDNI.setText("")
        self.lineEditDNI.setMaxLength(8)
        self.lineEditDNI.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEditDNI.setCursorPosition(0)
        self.lineEditDNI.setDragEnabled(False)
        self.lineEditDNI.setReadOnly(False)
        self.lineEditDNI.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.lineEditDNI.setClearButtonEnabled(True)
        self.lineEditDNI.setObjectName("lineEditDNI")
        self.horizontalLayout_2.addWidget(self.lineEditDNI)
        self.horizontalLayout_15.addWidget(self.frame_14, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.verticalLayout_16.addWidget(self.frame_12)
        self.labelRegistrado = QtWidgets.QLabel(parent=self.widget_5)
        self.labelRegistrado.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setItalic(True)
        self.labelRegistrado.setFont(font)
        self.labelRegistrado.setStyleSheet("color: rgb(46, 255, 60);")
        self.labelRegistrado.setObjectName("labelRegistrado")
        self.verticalLayout_16.addWidget(self.labelRegistrado)
        self.frame_13 = QtWidgets.QFrame(parent=self.widget_5)
        self.frame_13.setMinimumSize(QtCore.QSize(700, 60))
        self.frame_13.setMaximumSize(QtCore.QSize(9999, 60))
        self.frame_13.setStyleSheet("")
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_16.setContentsMargins(0, 0, 10, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.widget_6 = QtWidgets.QWidget(parent=self.frame_13)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_16 = QtWidgets.QLabel(parent=self.widget_6)
        self.label_16.setMinimumSize(QtCore.QSize(50, 0))
        self.label_16.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(104, 199, 107)")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_19.addWidget(self.label_16)
        self.labelDate = QtWidgets.QLabel(parent=self.widget_6)
        self.labelDate.setMaximumSize(QtCore.QSize(70, 30))
        self.labelDate.setObjectName("labelDate")
        self.horizontalLayout_19.addWidget(self.labelDate)
        self.horizontalLayout_16.addWidget(self.widget_6, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.widget_4 = QtWidgets.QWidget(parent=self.frame_13)
        self.widget_4.setMinimumSize(QtCore.QSize(120, 0))
        self.widget_4.setMaximumSize(QtCore.QSize(220, 16777215))
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.btnTodo = QtWidgets.QPushButton(parent=self.widget_4)
        self.btnTodo.setMinimumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setBold(True)
        self.btnTodo.setFont(font)
        self.btnTodo.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnTodo.setStyleSheet("\n"
"")
        self.btnTodo.setObjectName("btnTodo")
        self.horizontalLayout_14.addWidget(self.btnTodo)
        self.btnAsistio = QtWidgets.QPushButton(parent=self.widget_4)
        self.btnAsistio.setMinimumSize(QtCore.QSize(70, 30))
        self.btnAsistio.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        self.btnAsistio.setFont(font)
        self.btnAsistio.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnAsistio.setStyleSheet("")
        self.btnAsistio.setObjectName("btnAsistio")
        self.horizontalLayout_14.addWidget(self.btnAsistio)
        self.btnNoAsistio = QtWidgets.QPushButton(parent=self.widget_4)
        self.btnNoAsistio.setMinimumSize(QtCore.QSize(70, 30))
        self.btnNoAsistio.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        self.btnNoAsistio.setFont(font)
        self.btnNoAsistio.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnNoAsistio.setStyleSheet("")
        self.btnNoAsistio.setObjectName("btnNoAsistio")
        self.horizontalLayout_14.addWidget(self.btnNoAsistio)
        self.horizontalLayout_16.addWidget(self.widget_4)
        self.verticalLayout_16.addWidget(self.frame_13, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.widget_7 = QtWidgets.QWidget(parent=self.widget_5)
        self.widget_7.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.tablaTomarAsistencia = QtWidgets.QTableWidget(parent=self.widget_7)
        self.tablaTomarAsistencia.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tablaTomarAsistencia.sizePolicy().hasHeightForWidth())
        self.tablaTomarAsistencia.setSizePolicy(sizePolicy)
        self.tablaTomarAsistencia.setMinimumSize(QtCore.QSize(600, 300))
        self.tablaTomarAsistencia.setMaximumSize(QtCore.QSize(600, 600))
        self.tablaTomarAsistencia.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.tablaTomarAsistencia.setStyleSheet("QHeaderView::section {\n"
"   background-color: rgb(43, 69, 34);\n"
"   color: white;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    text-align: center; \n"
"}\n"
"\n"
"QTableWidget::indicator {\n"
"    width: 22px;\n"
"    height: 22px;\n"
"    border-radius: 11px;\n"
"    margin-left: auto;\n"
"    margin-right: auto;\n"
"    margin-top: auto;\n"
"    margin-bottom: auto;\n"
"}\n"
"QTableWidget::indicator:unchecked {\n"
"    background-color: red;\n"
"    image: url(:/icons/icons/frown.svg);\n"
"}\n"
"\n"
"QTableWidget::indicator:checked {\n"
"    background-color: green;\n"
"    image: url(:/icons/icons/smile.svg);\n"
"}")
        self.tablaTomarAsistencia.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.tablaTomarAsistencia.setLineWidth(1)
        self.tablaTomarAsistencia.setMidLineWidth(1)
        self.tablaTomarAsistencia.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.tablaTomarAsistencia.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.tablaTomarAsistencia.setAutoScroll(True)
        self.tablaTomarAsistencia.setAutoScrollMargin(4)
        self.tablaTomarAsistencia.setIconSize(QtCore.QSize(0, 0))
        self.tablaTomarAsistencia.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerItem)
        self.tablaTomarAsistencia.setGridStyle(QtCore.Qt.PenStyle.NoPen)
        self.tablaTomarAsistencia.setWordWrap(True)
        self.tablaTomarAsistencia.setObjectName("tablaTomarAsistencia")
        self.tablaTomarAsistencia.setColumnCount(4)
        self.tablaTomarAsistencia.setRowCount(13)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        item.setFont(font)
        self.tablaTomarAsistencia.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        item.setFont(font)
        self.tablaTomarAsistencia.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        item.setFont(font)
        self.tablaTomarAsistencia.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        item.setFont(font)
        self.tablaTomarAsistencia.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaTomarAsistencia.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        item.setFlags(QtCore.Qt.ItemFlag.ItemIsDragEnabled|QtCore.Qt.ItemFlag.ItemIsDropEnabled|QtCore.Qt.ItemFlag.ItemIsUserCheckable|QtCore.Qt.ItemFlag.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.CheckState.Checked)
        self.tablaTomarAsistencia.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.CheckState.Checked)
        self.tablaTomarAsistencia.setItem(1, 2, item)
        self.tablaTomarAsistencia.horizontalHeader().setVisible(True)
        self.tablaTomarAsistencia.horizontalHeader().setCascadingSectionResizes(False)
        self.tablaTomarAsistencia.horizontalHeader().setDefaultSectionSize(120)
        self.tablaTomarAsistencia.horizontalHeader().setSortIndicatorShown(False)
        self.tablaTomarAsistencia.horizontalHeader().setStretchLastSection(False)
        self.tablaTomarAsistencia.verticalHeader().setVisible(True)
        self.tablaTomarAsistencia.verticalHeader().setCascadingSectionResizes(False)
        self.tablaTomarAsistencia.verticalHeader().setHighlightSections(False)
        self.tablaTomarAsistencia.verticalHeader().setSortIndicatorShown(False)
        self.horizontalLayout_20.addWidget(self.tablaTomarAsistencia, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.btnGeneraReporte = QtWidgets.QPushButton(parent=self.widget_7)
        font = QtGui.QFont()
        font.setBold(True)
        self.btnGeneraReporte.setFont(font)
        self.btnGeneraReporte.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnGeneraReporte.setStyleSheet("border-radius: 12px;")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/icons/file-text.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnGeneraReporte.setIcon(icon12)
        self.btnGeneraReporte.setObjectName("btnGeneraReporte")
        self.horizontalLayout_20.addWidget(self.btnGeneraReporte)
        self.verticalLayout_16.addWidget(self.widget_7)
        self.verticalLayout_19.addWidget(self.widget_5)
        self.mainStackedWidget.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_8)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_8 = QtWidgets.QWidget(parent=self.page_8)
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_8)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_10 = QtWidgets.QWidget(parent=self.widget_8)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_5 = QtWidgets.QLabel(parent=self.widget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_25.addWidget(self.label_5)
        self.label_8 = QtWidgets.QLabel(parent=self.widget_10)
        self.label_8.setMinimumSize(QtCore.QSize(300, 0))
        self.label_8.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_25.addWidget(self.label_8)
        self.gridLayout_4.addWidget(self.widget_10, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignTop)
        self.gridLayout_3.addWidget(self.widget_8, 0, 0, 1, 1)
        self.widget_9 = QtWidgets.QWidget(parent=self.page_8)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_18 = QtWidgets.QLabel(parent=self.widget_9)
        self.label_18.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_24.addWidget(self.label_18)
        self.label_21 = QtWidgets.QLabel(parent=self.widget_9)
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_21.setObjectName("label_21")
        self.verticalLayout_24.addWidget(self.label_21)
        self.label_17 = QtWidgets.QLabel(parent=self.widget_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_24.addWidget(self.label_17)
        self.gridLayout_3.addWidget(self.widget_9, 0, 1, 1, 1, QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_10 = QtWidgets.QLabel(parent=self.page_8)
        self.label_10.setMaximumSize(QtCore.QSize(200, 200))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(":/images/universidad-continental LOGO blanco.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 1, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.gifProgramador = QtWidgets.QLabel(parent=self.page_8)
        self.gifProgramador.setText("")
        self.gifProgramador.setPixmap(QtGui.QPixmap(":/images/programador.gif"))
        self.gifProgramador.setObjectName("gifProgramador")
        self.gridLayout_3.addWidget(self.gifProgramador, 2, 0, 1, 1)
        self.mainStackedWidget.addWidget(self.page_8)
        self.verticalLayout_20.addWidget(self.mainStackedWidget)
        self.popupNotificationContainer = QtWidgets.QWidget(parent=self.mainContentsContainer)
        self.popupNotificationContainer.setObjectName("popupNotificationContainer")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.popupNotificationContainer)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.popupNotificationSubContainer = QtWidgets.QWidget(parent=self.popupNotificationContainer)
        self.popupNotificationSubContainer.setEnabled(True)
        self.popupNotificationSubContainer.setObjectName("popupNotificationSubContainer")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.popupNotificationSubContainer)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_9 = QtWidgets.QFrame(parent=self.popupNotificationSubContainer)
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelMsgNotification = QtWidgets.QLabel(parent=self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelMsgNotification.sizePolicy().hasHeightForWidth())
        self.labelMsgNotification.setSizePolicy(sizePolicy)
        self.labelMsgNotification.setObjectName("labelMsgNotification")
        self.gridLayout_2.addWidget(self.labelMsgNotification, 1, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.labelTitleNotification = QtWidgets.QLabel(parent=self.frame_9)
        font = QtGui.QFont()
        font.setBold(True)
        self.labelTitleNotification.setFont(font)
        self.labelTitleNotification.setObjectName("labelTitleNotification")
        self.gridLayout_2.addWidget(self.labelTitleNotification, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignTop)
        self.btnCloseNotification = QtWidgets.QPushButton(parent=self.frame_9)
        self.btnCloseNotification.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCloseNotification.setText("")
        self.btnCloseNotification.setIcon(icon5)
        self.btnCloseNotification.setIconSize(QtCore.QSize(24, 24))
        self.btnCloseNotification.setObjectName("btnCloseNotification")
        self.gridLayout_2.addWidget(self.btnCloseNotification, 0, 1, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout_18.addWidget(self.frame_9)
        self.verticalLayout_17.addWidget(self.popupNotificationSubContainer)
        self.verticalLayout_20.addWidget(self.popupNotificationContainer)
        self.horizontalLayout_8.addWidget(self.mainContentsContainer)
        self.rightMenuContainer = QtWidgets.QWidget(parent=self.mainBodyContent)
        self.rightMenuContainer.setMinimumSize(QtCore.QSize(200, 0))
        self.rightMenuContainer.setObjectName("rightMenuContainer")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.rightMenuContainer)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.rightMenuSubContainer = QtWidgets.QWidget(parent=self.rightMenuContainer)
        self.rightMenuSubContainer.setMinimumSize(QtCore.QSize(250, 0))
        self.rightMenuSubContainer.setMaximumSize(QtCore.QSize(250, 16777215))
        self.rightMenuSubContainer.setObjectName("rightMenuSubContainer")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.rightMenuSubContainer)
        self.verticalLayout_12.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_12.setSpacing(5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_8 = QtWidgets.QFrame(parent=self.rightMenuSubContainer)
        self.frame_8.setMinimumSize(QtCore.QSize(180, 40))
        self.frame_8.setMaximumSize(QtCore.QSize(300, 40))
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_7.setMinimumSize(QtCore.QSize(50, 0))
        self.label_7.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.btnCloseProfile = QtWidgets.QPushButton(parent=self.frame_8)
        self.btnCloseProfile.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCloseProfile.setText("")
        self.btnCloseProfile.setIcon(icon5)
        self.btnCloseProfile.setIconSize(QtCore.QSize(24, 24))
        self.btnCloseProfile.setObjectName("btnCloseProfile")
        self.horizontalLayout_9.addWidget(self.btnCloseProfile, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout_12.addWidget(self.frame_8)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(parent=self.rightMenuSubContainer)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.widget_3 = QtWidgets.QWidget(parent=self.page_4)
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.profeFoto = QtWidgets.QLabel(parent=self.widget_3)
        self.profeFoto.setMaximumSize(QtCore.QSize(40, 40))
        self.profeFoto.setText("")
        self.profeFoto.setPixmap(QtGui.QPixmap(":/images/fotoIngJudithRounded.png"))
        self.profeFoto.setScaledContents(True)
        self.profeFoto.setObjectName("profeFoto")
        self.horizontalLayout_10.addWidget(self.profeFoto)
        spacerItem1 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.lblNombreDocente = QtWidgets.QLabel(parent=self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblNombreDocente.setFont(font)
        self.lblNombreDocente.setObjectName("lblNombreDocente")
        self.horizontalLayout_10.addWidget(self.lblNombreDocente)
        self.verticalLayout_21.addWidget(self.widget_3)
        self.widget_2 = QtWidgets.QWidget(parent=self.page_4)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 200))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 220))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_19 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_15.addWidget(self.label_19)
        self.lblCorreoDocente = QtWidgets.QLabel(parent=self.widget_2)
        self.lblCorreoDocente.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lblCorreoDocente.setObjectName("lblCorreoDocente")
        self.verticalLayout_15.addWidget(self.lblCorreoDocente)
        self.label_20 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_15.addWidget(self.label_20)
        self.lblPaisDocente = QtWidgets.QLabel(parent=self.widget_2)
        self.lblPaisDocente.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lblPaisDocente.setObjectName("lblPaisDocente")
        self.verticalLayout_15.addWidget(self.lblPaisDocente)
        self.label_23 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_15.addWidget(self.label_23)
        self.lblCiudadDocente = QtWidgets.QLabel(parent=self.widget_2)
        self.lblCiudadDocente.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lblCiudadDocente.setObjectName("lblCiudadDocente")
        self.verticalLayout_15.addWidget(self.lblCiudadDocente)
        self.verticalLayout_21.addWidget(self.widget_2, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.stackedWidget_2.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_9 = QtWidgets.QLabel(parent=self.page_5)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_13.addWidget(self.label_9)
        self.stackedWidget_2.addWidget(self.page_5)
        self.verticalLayout_12.addWidget(self.stackedWidget_2, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout_11.addWidget(self.rightMenuSubContainer, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.horizontalLayout_8.addWidget(self.rightMenuContainer)
        self.verticalLayout_10.addWidget(self.mainBodyContent)
        self.footerContainer = QtWidgets.QWidget(parent=self.mainBodyContainer)
        self.footerContainer.setObjectName("footerContainer")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.footerContainer)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_10 = QtWidgets.QFrame(parent=self.footerContainer)
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_15 = QtWidgets.QLabel(parent=self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_13.addWidget(self.label_15)
        self.horizontalLayout_12.addWidget(self.frame_10)
        self.sizeGrip = QtWidgets.QFrame(parent=self.footerContainer)
        self.sizeGrip.setMinimumSize(QtCore.QSize(30, 30))
        self.sizeGrip.setMaximumSize(QtCore.QSize(30, 30))
        self.sizeGrip.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.sizeGrip.setObjectName("sizeGrip")
        self.horizontalLayout_12.addWidget(self.sizeGrip)
        self.verticalLayout_10.addWidget(self.footerContainer)
        self.horizontalLayout.addWidget(self.mainBodyContainer)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionSalir = QtGui.QAction(parent=MainWindow)
        self.actionSalir.setObjectName("actionSalir")

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.mainStackedWidget.setCurrentIndex(2)
        self.stackedWidgetCursos.setCurrentIndex(0)
        self.cmbBoxAsignatura.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gestión de Asistencia en Aula"))
        self.pushButtonInicio.setToolTip(_translate("MainWindow", "Inicio"))
        self.pushButtonInicio.setText(_translate("MainWindow", "Inicio"))
        self.pushButtonAsistencia.setToolTip(_translate("MainWindow", "Tomar la asistencia"))
        self.pushButtonAsistencia.setText(_translate("MainWindow", "Asistencia"))
        self.pushButtonAcercaDe.setToolTip(_translate("MainWindow", "Ver información"))
        self.pushButtonAcercaDe.setText(_translate("MainWindow", "Acerca de"))
        self.btnCerrarSesion.setToolTip(_translate("MainWindow", "Ver la ayuda"))
        self.btnCerrarSesion.setText(_translate("MainWindow", "Cerrar Sesión"))
        self.label.setText(_translate("MainWindow", "Información"))
        self.btnCloseMoreMenu.setToolTip(_translate("MainWindow", "Cerrar Menú"))
        self.label_2.setText(_translate("MainWindow", "Settings"))
        self.label_3.setText(_translate("MainWindow", "Help"))
        self.label_4.setText(_translate("MainWindow", "Information"))
        self.label_6.setText(_translate("MainWindow", "TRICAPP"))
        self.btnNotification.setToolTip(_translate("MainWindow", "Más"))
        self.btnProfile.setToolTip(_translate("MainWindow", "Perfil"))
        self.minimizeBtn.setToolTip(_translate("MainWindow", "Minimizar"))
        self.restoreBtn.setToolTip(_translate("MainWindow", "Restaurar"))
        self.closeBtn.setToolTip(_translate("MainWindow", "Cerrar"))
        self.lblSaludoInicio.setText(_translate("MainWindow", "Hola Judith"))
        self.btnCurso22888.setText(_translate("MainWindow", "22888 - DIRECCIÓN DE PROYECTOS"))
        self.btnCurso12341.setText(_translate("MainWindow", "12341 - ASIGNATURA 1 / TEST"))
        self.btnCurso12342.setText(_translate("MainWindow", "12342 - ASIGNATURA 2 / TEST"))
        self.btnCurso12343.setText(_translate("MainWindow", "12343 - ASIGNATURA 3 / TEST"))
        self.btnCurso30246.setText(_translate("MainWindow", "30246 - INNOVACIÓN SOCIAL"))
        self.btnCurso12344.setText(_translate("MainWindow", "12344 - ASIGNATURA 4 / TEST"))
        self.btnCurso12345.setText(_translate("MainWindow", "12345 - ASIGNATURA 5 / TEST"))
        self.label_11.setText(_translate("MainWindow", "Asignatura: "))
        self.cmbBoxAsignatura.setItemText(0, _translate("MainWindow", "QUÍMICA 1-31979"))
        self.cmbBoxAsignatura.setItemText(1, _translate("MainWindow", "QUÍMICA-31962"))
        self.cmbBoxAsignatura.setItemText(2, _translate("MainWindow", "DIRECCIÓN DE PROYECTOS-22892"))
        self.cmbBoxAsignatura.setItemText(3, _translate("MainWindow", "DIRECCIÓN DE PROYECTOS-22888"))
        self.cmbBoxAsignatura.setItemText(4, _translate("MainWindow", "INNOVACIÓN SOCIAL-30246"))
        self.labelAsistioDNI.setText(_translate("MainWindow", "Asistencia por DNI:"))
        self.lineEditDNI.setToolTip(_translate("MainWindow", "Enter para registrar asistencia"))
        self.lineEditDNI.setPlaceholderText(_translate("MainWindow", "12345678"))
        self.labelRegistrado.setText(_translate("MainWindow", "DNI Registrado"))
        self.label_16.setText(_translate("MainWindow", "Fecha:"))
        self.labelDate.setText(_translate("MainWindow", "18/05/2024"))
        self.btnTodo.setText(_translate("MainWindow", "Todo"))
        self.btnAsistio.setText(_translate("MainWindow", "Asistió"))
        self.btnNoAsistio.setText(_translate("MainWindow", "No asistió"))
        self.tablaTomarAsistencia.setSortingEnabled(False)
        item = self.tablaTomarAsistencia.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "DNI"))
        item = self.tablaTomarAsistencia.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Estudiante"))
        item = self.tablaTomarAsistencia.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Estado de asistencia"))
        item = self.tablaTomarAsistencia.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Hora de registro"))
        __sortingEnabled = self.tablaTomarAsistencia.isSortingEnabled()
        self.tablaTomarAsistencia.setSortingEnabled(False)
        item = self.tablaTomarAsistencia.item(0, 0)
        item.setText(_translate("MainWindow", "wdwdwdw"))
        self.tablaTomarAsistencia.setSortingEnabled(__sortingEnabled)
        self.btnGeneraReporte.setText(_translate("MainWindow", "Generar \n"
"reporte"))
        self.label_5.setText(_translate("MainWindow", "Equipo de desarrollo"))
        self.label_8.setText(_translate("MainWindow", "Jefe de proyecto: George Calderon Lopez\n"
"Diseñador: Yoni Gonzales Orihuela\n"
"Programador: García Betancourt Josué\n"
"Pruebas: Raúl Torre Medina\n"
"Implementación: David Contreras Cerrón"))
        self.label_18.setText(_translate("MainWindow", "Sobre TRICAPP"))
        self.label_21.setText(_translate("MainWindow", "Gestor de Sueldos V1 permite al usuario realizar los cálculos \n"
"mensuales de sueldos de los trabajadores registrados."))
        self.label_17.setText(_translate("MainWindow", "Fecha de despliegue: 25/06/2023 \n"
" Copyright © UC Company"))
        self.labelMsgNotification.setText(_translate("MainWindow", "Aún no tienes notificaciones pendientes, vuelve pronto. "))
        self.labelTitleNotification.setText(_translate("MainWindow", "Notificación"))
        self.btnCloseNotification.setToolTip(_translate("MainWindow", "Cerrar notificación"))
        self.label_7.setText(_translate("MainWindow", "Perfil"))
        self.btnCloseProfile.setToolTip(_translate("MainWindow", "Cerrar Menu"))
        self.lblNombreDocente.setText(_translate("MainWindow", "Judith Camarena Flores"))
        self.label_19.setText(_translate("MainWindow", "Dirección de correo\n"
""))
        self.lblCorreoDocente.setText(_translate("MainWindow", "jcamarenaf@continental.edu.pe"))
        self.label_20.setText(_translate("MainWindow", "País"))
        self.lblPaisDocente.setText(_translate("MainWindow", "Perú"))
        self.label_23.setText(_translate("MainWindow", "Ciudad"))
        self.lblCiudadDocente.setText(_translate("MainWindow", "Huancayo"))
        self.label_9.setText(_translate("MainWindow", "More..."))
        self.label_15.setText(_translate("MainWindow", "Universidad Continental | Huancayo - Perú"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
